'use strict';

module.exports = function(hectic) {
  return {
    link: { direction: new hectic.primitives.Enum('north', 'east', 'south', 'west',
      'up', 'down',
      'northeast', 'southeast',
      'northwest', 'southwest') },
    door: { state: new hectic.primitives.Enum('open', 'closed', 'locked',
      'sealed', 'smashed') },
    object: { type: new hectic.primitives.Enum(
      'ammo',
      'bottle',
      'clothing',
      'communicator',
      'consumable',
      'container',
      'data',
      'device',
      'display',
      'drug',
      'food',
      'furniture',
      'identification',
      'inanimate',
      'key',
      'liquid',
      'medicine',
      'money',
      'ridable',
      'robot',
      'scenery',
      'trash',
      'treasure',
      'vegetation',
      'weapon',
      'wearable',
      'writable') },
    player: { position: new hectic.primitives.Enum('dead', 'mortally-wounded',
      'incapacitated', 'stunned',
      'sleeping', 'resting',
      'sitting', 'riding',
      'fighting',
      'standing') }
  };
};
